using System.Globalization;
using System.Text;
using SignsOfAI.Core.Calibration;

namespace SignsOfAI.Calibration;

/// <summary>One window cut from a document, and what the analyzer made of it.</summary>
public sealed record WindowMeasurement
{
    /// <summary>Where in the document's prose the window starts, as a label a reader understands.</summary>
    public required string Position { get; init; }

    public required double Score { get; init; }

    public required double Burstiness { get; init; }

    public required int Words { get; init; }
}

/// <summary>One text seen twice, and what the analyzer said about each half.</summary>
public sealed record PairMeasurement
{
    public required string Id { get; init; }

    public required string Language { get; init; }

    public required string Stratum { get; init; }

    public required double HumanScore { get; init; }

    public required double RewrittenScore { get; init; }

    public required double HumanBurstiness { get; init; }

    public required double RewrittenBurstiness { get; init; }

    public required int HumanWords { get; init; }

    public required int RewrittenWords { get; init; }

    /// <summary>Rules that produced evidence — the ones that scored, not those found at a human rate.</summary>
    public required IReadOnlyList<string> HumanRuleIds { get; init; }

    public required IReadOnlyList<string> RewrittenRuleIds { get; init; }

    public required int HumanArtifacts { get; init; }

    public required int RewrittenArtifacts { get; init; }

    /// <summary>Every artifact codepoint found, so the report can name them instead of counting them.</summary>
    public IReadOnlyList<string> ArtifactCodePoints { get; init; } = [];

    /// <summary>The whole document the excerpt was cut from. Null when the source is not on this machine.</summary>
    public double? FullScore { get; init; }

    public double? FullBurstiness { get; init; }

    public int FullWords { get; init; }

    /// <summary>
    /// The same document with its figure captions and boilerplate stripped by the filter the excerpts
    /// already pass through — the control that tells composition apart from length.
    /// </summary>
    public double? ProseOnlyScore { get; init; }

    /// <summary>Fixed-length windows cut at several positions, which is how the length arm is measured.</summary>
    public IReadOnlyList<WindowMeasurement> Windows { get; init; } = [];

    /// <summary>Longest run of consecutive words from the original surviving verbatim in the rewrite.</summary>
    public int LongestRun { get; init; }

    /// <summary>Share of the rewrite sitting inside verbatim runs of eight words or more.</summary>
    public double ShareRetained { get; init; }

    public double Delta => RewrittenScore - HumanScore;
}

/// <summary>
/// Renders what a machine rewrite does to writing that is known to be human.
///
/// Three reviewers went over the first version of this page adversarially and the arithmetic
/// survived; the prose did not. Three sentences were false — a window described as coming from the
/// middle of a document that was cut from its opening, a deviation log calling one breach unique
/// when half the pairs contained one, and a directional claim asserted on evidence that failed the
/// exact test applied two paragraphs above it. All three were the same failure: a page that machine
/// checks its numbers and hand-waves its method. Everything the method now claims is measured by the
/// code below and printed whether or not it flatters the study.
///
/// The page also has to survive being read once, quickly, by a teacher with no statistics. That is
/// the reader this project exists for, and a headline they misread is worse than one they skip.
/// </summary>
public static class ParaphraseReport
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Render(
        IReadOnlyList<PairMeasurement> pairs,
        PairManifest manifest,
        double threshold,
        string version,
        string generatedOn)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# What a machine rewrite does to human writing");
        sb.AppendLine();
        sb.AppendLine("<!-- Generated by tools/SignsOfAI.Calibration. Do not edit by hand: re-run it. -->");
        sb.AppendLine();
        sb.AppendLine(
            "Claude models released on or after 2 August 2026 carry a machine-readable watermark, and " +
            "Anthropic says earlier ones will follow during a transition period. The technique is a " +
            "version of SynthID-Text, published by Google DeepMind in 2024 and already in use " +
            "elsewhere — this is an industry practice arriving at one more vendor, not a new " +
            "invention. The mark lives in which words the model chose, so cleaning invisible " +
            "characters cannot touch it, and the vendor's help centre names heavy editing, " +
            "paraphrasing, translation, mixing into other writing and very short passages as things " +
            "that leave it undetectable. Services selling that rewrite already exist.");
        sb.AppendLine();
        sb.AppendLine(
            "This page measures what such a rewrite does to a passage, using passages whose author " +
            "was demonstrably a person.");
        sb.AppendLine();

        if (pairs.Count == 0)
        {
            sb.AppendLine("**No pairs were measured, so there is nothing to report.** " +
                          "See `Docs/Paraphrase/README.md` for how to build them.");
            return sb.ToString();
        }

        // ---- method --------------------------------------------------------------------------
        sb.AppendLine("## What was measured");
        sb.AppendLine();
        sb.AppendLine($"- **Pairs** {pairs.Count} passages, each measured as written and as rewritten");
        sb.AppendLine($"- **Drawn from** corpus `{manifest.CorpusId}`, the same texts as `Docs/CALIBRATION.md`");
        sb.AppendLine($"- **Rewritten by** {manifest.ParaphrasedBy ?? "unrecorded"} on {manifest.ParaphrasedOn ?? "an unrecorded date"}");
        sb.AppendLine("- **Instruction** `Docs/Paraphrase/instruction.md`, stored verbatim");
        sb.AppendLine($"- **Engine** {version}, verdict boundary {threshold.ToString("0", Inv)}/100");
        sb.AppendLine($"- **Pair fingerprint** `{manifest.Fingerprint()}`");
        sb.AppendLine($"- **Run** {generatedOn}");
        sb.AppendLine();
        sb.AppendLine(
            "Every human half was published before generative models existed, which is the whole basis " +
            "for calling it human and the same basis the calibration page rests on. Both halves are the " +
            "same passage at roughly the same length, so the comparison is within a text rather than " +
            "between two populations: no collection of machine-written prose was assembled, and none " +
            "was needed. The pairs are cut from the **opening** of each document, which matters and is " +
            "measured under Length.");
        sb.AppendLine();
        sb.AppendLine(
            "**This half of the study ages, and the human half does not.** A 2019 paper will still have " +
            "been written in 2019 a decade from now; the rewrite is the work of one model on one day. " +
            "That is why the model and the date are printed above rather than buried, and why the right " +
            "response to \"but a newer model rewrites differently\" is to re-run this with that model " +
            "rather than to argue about it.");
        sb.AppendLine();

        // ---- headline ------------------------------------------------------------------------
        int flaggedBefore = pairs.Count(p => p.HumanScore >= threshold);
        int flaggedAfter = pairs.Count(p => p.RewrittenScore >= threshold);
        var (beforeLow, beforeHigh) = Calibrator.WilsonInterval(flaggedBefore, pairs.Count);
        var (afterLow, afterHigh) = Calibrator.WilsonInterval(flaggedAfter, pairs.Count);

        int becameFlagged = pairs.Count(p => p.HumanScore < threshold && p.RewrittenScore >= threshold);
        int becameClean = pairs.Count(p => p.HumanScore >= threshold && p.RewrittenScore < threshold);
        double mcnemar = ExactBinomialTwoSided(becameFlagged, becameFlagged + becameClean);

        var withFull = pairs.Where(x => x.FullScore is not null).ToList();
        int flaggedFull = withFull.Count(x => x.FullScore >= threshold);
        var windows = pairs.SelectMany(p => p.Windows).ToList();
        int flaggedWindows = windows.Count(w => w.Score >= threshold);

        sb.AppendLine("## The short version");
        sb.AppendLine();
        sb.AppendLine(
            "**Having a language model rewrite a passage did not change whether this tool flagged it. " +
            "Cutting the same passage down to four hundred words did.**");
        sb.AppendLine();
        sb.AppendLine(
            "That is the opposite of what this study set out to find, and the second half of it is a " +
            "fault in this tool rather than a finding about anybody's watermark. Neither sentence " +
            "should be read as *the tool catches rewritten work*: it does not, and this page is the " +
            "evidence that it does not.");
        sb.AppendLine();
        if (withFull.Count > 0 && windows.Count > 0)
        {
            var (wLow, wHigh) = Calibrator.WilsonInterval(flaggedWindows, windows.Count);
            sb.AppendLine($"| Same writing, measured as | Flagged at {threshold.ToString("0", Inv)}/100 | Rate | 95% interval |");
            sb.AppendLine("|---|---|---|---|");
            sb.AppendLine($"| whole documents | {flaggedFull} / {withFull.Count} | {Pct(Rate(flaggedFull, withFull.Count))} | {Wilson(flaggedFull, withFull.Count)} |");
            sb.AppendLine($"| {manifest.TargetWords}-word windows, three positions each | {flaggedWindows} / {windows.Count} | {Pct(Rate(flaggedWindows, windows.Count))} | {Pct(wLow)} – {Pct(wHigh)} |");
            sb.AppendLine($"| the opening window, as written | {flaggedBefore} / {pairs.Count} | {Pct(Rate(flaggedBefore, pairs.Count))} | {Pct(beforeLow)} – {Pct(beforeHigh)} |");
            sb.AppendLine($"| the opening window, rewritten | {flaggedAfter} / {pairs.Count} | {Pct(Rate(flaggedAfter, pairs.Count))} | {Pct(afterLow)} – {Pct(afterHigh)} |");
            sb.AppendLine();
        }

        sb.AppendLine("### The rewrite, measured against the passage it came from");
        sb.AppendLine();
        sb.AppendLine(
            $"{becameFlagged} passages crossed the boundary that had not, {becameClean} crossed back, " +
            $"and the other {pairs.Count - becameFlagged - becameClean} stayed where they were. " +
            $"McNemar's exact test on the discordant pairs gives {FormatP(mcnemar)}. With " +
            $"{becameFlagged + becameClean} pairs changing side at all, only a clean sweep would have " +
            "reached significance, so the honest statement is that **this study cannot show that " +
            "rewriting changes whether a passage is flagged, in either direction** — not that it " +
            "showed rewriting is safe, and not that it showed rewriting is caught.");
        sb.AppendLine();

        // ---- treatment fidelity -----------------------------------------------------------------
        var breaches = pairs.Where(p => p.LongestRun >= Fidelity.MaximumRun).ToList();
        var retained = pairs.Select(p => p.ShareRetained).OrderBy(s => s).ToList();

        sb.AppendLine("## Was the treatment actually applied");
        sb.AppendLine();
        sb.AppendLine(
            "The instruction asks that no run of eight or more consecutive words survive. Whether it " +
            "did is checked here rather than attested, because the first version of this study " +
            "attested it by hand and the hand was wrong.");
        sb.AppendLine();
        sb.AppendLine($"- **{breaches.Count} of {pairs.Count} pairs** contain at least one surviving run of " +
                      $"{Fidelity.MaximumRun} words or more");
        sb.AppendLine($"- **Longest run** {pairs.Max(p => p.LongestRun)} words");
        sb.AppendLine($"- **Share of each rewrite inside such runs** median {Pct(Quantile(retained, 0.5))}, " +
                      $"highest {Pct(retained[^1])}");
        sb.AppendLine();
        if (breaches.Count > 0)
        {
            sb.AppendLine("| Pair | Longest run | Share retained |");
            sb.AppendLine("|---|---|---|");
            foreach (var p in breaches.OrderByDescending(p => p.LongestRun).Take(8))
                sb.AppendLine($"| `{p.Id}` | {p.LongestRun} | {Pct(p.ShareRetained)} |");
            sb.AppendLine();
        }
        sb.AppendLine(
            "The long runs are quotations. A passage that quotes a court ruling, a political pamphlet " +
            "or a published definition cannot have those words replaced without falsifying them, and " +
            "the instruction's own requirement to preserve every fact and citation marker conflicts " +
            "with its word-run limit; the protocol never said which wins. The shorter runs are names, " +
            "dates and technical terms.");
        sb.AppendLine();
        sb.AppendLine(
            "**The consequence is that the delivered treatment is a partial rewrite**, weaker than the " +
            "one the opening of this page describes. That biases every paired difference toward zero — " +
            "toward the null result reported above. The null is therefore measured under a treatment " +
            "milder than intended, which makes it weaker evidence than it looks, not stronger.");
        sb.AppendLine();

        // ---- length ----------------------------------------------------------------------------
        if (withFull.Count > 0 && windows.Count > 0)
        {
            AppendLength(sb, pairs, withFull, windows, manifest, threshold);
        }

        // ---- scores --------------------------------------------------------------------------
        var deltas = pairs.Select(x => x.Delta).OrderBy(d => d).ToList();
        int rose = pairs.Count(x => x.Delta > 0);
        int fell = pairs.Count(x => x.Delta < 0);
        var (scoreLow, scoreHigh) = MedianInterval(deltas);

        sb.AppendLine("## How far the score moved");
        sb.AppendLine();
        sb.AppendLine("| | Median | 90th percentile | Highest |");
        sb.AppendLine("|---|---|---|---|");
        AppendScoreRow(sb, "As written", [.. pairs.Select(x => x.HumanScore)]);
        AppendScoreRow(sb, "Rewritten", [.. pairs.Select(x => x.RewrittenScore)]);
        sb.AppendLine();
        sb.AppendLine(
            $"The score rose in {rose} pairs, fell in {fell} and was unchanged in " +
            $"{pairs.Count - rose - fell}. Taking each passage against itself, the median change is " +
            $"{Signed(Quantile(deltas, 0.5))} points (95% interval {Signed(scoreLow)} to {Signed(scoreHigh)}), " +
            $"with the middle half between {Signed(Quantile(deltas, 0.25))} and {Signed(Quantile(deltas, 0.75))}. " +
            $"An exact sign test on the {rose + fell} pairs that moved gives {FormatP(ExactBinomialTwoSided(Math.Min(rose, fell), rose + fell))}, " +
            $"and Wilcoxon signed-rank {FormatP(WilcoxonSignedRank(deltas))}. **The direction is not " +
            "established.** The rewrite strips the vocabulary of academic prose — *furthermore*, " +
            "*comprehensive*, *facilitate*, *utilizar* — while flattening sentence rhythm, and on this " +
            "sample the two effects are not separable from each other or from noise.");
        sb.AppendLine();

        // ---- burstiness ----------------------------------------------------------------------
        var burstBefore = pairs.Select(x => x.HumanBurstiness).OrderBy(b => b).ToList();
        var burstAfter = pairs.Select(x => x.RewrittenBurstiness).OrderBy(b => b).ToList();
        var burstDeltas = pairs.Select(x => x.RewrittenBurstiness - x.HumanBurstiness).OrderBy(d => d).ToList();
        int burstFell = pairs.Count(x => x.RewrittenBurstiness < x.HumanBurstiness);
        int burstRose = pairs.Count(x => x.RewrittenBurstiness > x.HumanBurstiness);
        var (burstLow, burstHigh) = MedianInterval(burstDeltas);

        sb.AppendLine("## Burstiness");
        sb.AppendLine();
        sb.AppendLine(
            "Sentence-length variation is the signal this project trusts most, because it needs no " +
            "word list and no model. Human prose is uneven; unprompted model output tends to settle " +
            "into a width and stay there.");
        sb.AppendLine();
        sb.AppendLine($"- **As written** median {Quantile(burstBefore, 0.5).ToString("0.00", Inv)}, " +
                      $"range {burstBefore[0].ToString("0.00", Inv)} – {burstBefore[^1].ToString("0.00", Inv)}");
        sb.AppendLine($"- **Rewritten** median {Quantile(burstAfter, 0.5).ToString("0.00", Inv)}, " +
                      $"range {burstAfter[0].ToString("0.00", Inv)} – {burstAfter[^1].ToString("0.00", Inv)}");
        sb.AppendLine($"- **Paired change** median {Signed(Quantile(burstDeltas, 0.5), "0.00")} " +
                      $"(95% interval {Signed(burstLow, "0.00")} to {Signed(burstHigh, "0.00")}), " +
                      $"falling in {burstFell} of {pairs.Count} pairs");
        sb.AppendLine();
        sb.AppendLine(
            $"This is the closest the study comes to a directional effect, and it is not clean. An " +
            $"exact sign test on {burstFell} falls against {burstRose} rises gives " +
            $"{FormatP(ExactBinomialTwoSided(Math.Min(burstFell, burstRose), burstFell + burstRose))} — " +
            "by the same standard applied to the flag counts above, not a result. Wilcoxon " +
            $"signed-rank, which uses the size of each change and not only its direction, gives " +
            $"{FormatP(WilcoxonSignedRank(burstDeltas))}. Neither test was chosen in advance, so the " +
            "honest reading is that **the rewrite probably flattens rhythm slightly and this sample " +
            "cannot settle it**. A few hundredths on a scale where human prose runs from roughly 0.2 " +
            "to 0.9 moves almost nothing on its own.");
        sb.AppendLine();

        // ---- what fires ----------------------------------------------------------------------
        AppendRuleTables(sb, pairs);

        // ---- characters ----------------------------------------------------------------------
        AppendCharacters(sb, pairs);

        // ---- by language ---------------------------------------------------------------------
        sb.AppendLine("## By language");
        sb.AppendLine();
        sb.AppendLine(
            "A result that holds in English and fails in Spanish is not one result. Two warnings " +
            "before the table: the Spanish arm is eight pairs, all encyclopedia entries, so it is " +
            "also a single-source arm and cannot be compared cleanly with an English arm that mixes " +
            "research articles and encyclopedia entries. And eight pairs support no interval worth " +
            "printing.");
        sb.AppendLine();
        AppendGroupTable(sb, pairs.GroupBy(x => x.Language, StringComparer.OrdinalIgnoreCase), threshold);
        AppendGroupTable(sb, pairs.GroupBy(x => x.Stratum, StringComparer.OrdinalIgnoreCase), threshold);

        // ---- conflict of interest ----------------------------------------------------------------
        sb.AppendLine("## The conflict of interest");
        sb.AppendLine();
        sb.AppendLine(
            $"The rewriting was done by {manifest.ParaphrasedBy ?? "an unrecorded model"}. Two things " +
            "follow that naming the model does not cover.");
        sb.AppendLine();
        sb.AppendLine(
            "**The rewriter's vendor is the vendor whose watermark prompted the study.** And more " +
            "seriously, the same model wrote this project's rule packs, this tool, and the prose on " +
            "this page. The instruction's defences are all at the level of the prompt — it mentions " +
            "no detector and names no tell — and the contamination risk is at the level of knowledge: " +
            "a model that wrote the rule for *furthermore* does not need to be told to avoid it. The " +
            "removed-signals table above is exactly what tell-aware avoidance would produce.");
        sb.AppendLine();
        sb.AppendLine(
            "What argues against it is also on this page: the rewrite *introduced* tells as well as " +
            "removing them, and pushed more passages over the boundary than it pulled back. A model " +
            "gaming the measurement would not do that. But the objection is legitimate, it is the " +
            "first one a hostile reader will raise, and the only real answer is a second rewriter " +
            "from a different vendor. **Until that exists, these numbers should not be quoted " +
            "anywhere a teacher will act on them.**");
        sb.AppendLine();

        // ---- limits ------------------------------------------------------------------------------
        sb.AppendLine("## What this does not tell you");
        sb.AppendLine();
        sb.AppendLine("- **Nothing about detecting a watermark.** The key is Anthropic's and no third " +
                      "party holds it. This measures what happens to *prose*, which is a different " +
                      "question that happens to be answerable without anybody's permission.");
        sb.AppendLine("- **Nothing about how much machine writing this tool catches.** That would need " +
                      "a corpus of machine writing, which `Docs/Calibration/README.md` argues at length " +
                      "against assembling, and the argument has not changed.");
        sb.AppendLine("- **Nothing about whether rewriting helps or hurts a student.** The study " +
                      "failed to establish a direction. Anyone quoting it in either direction is " +
                      "quoting something that is not here.");
        sb.AppendLine("- **One model, one instruction, one day**, and the treatment was only partly " +
                      "delivered. All of that is above.");
        sb.AppendLine("- **These are published articles and encyclopedia entries**, not student essays, " +
                      "and the windows are cut from them rather than composed at that length. A " +
                      "four-hundred-word paragraph somebody wrote as a paragraph has a whole " +
                      "distribution of sentence lengths; a truncation does not.");
        sb.AppendLine($"- **{pairs.Count} pairs is a small study.** Read the intervals rather than the " +
                      "percentages.");
        sb.AppendLine();
        sb.AppendLine("Re-run it yourself:");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("dotnet run --project tools/SignsOfAI.Calibration -- excerpt --per-stratum 8");
        sb.AppendLine("# rewrite each passage in Docs/Paraphrase/human/ into Docs/Paraphrase/rewritten/");
        sb.AppendLine("dotnet run --project tools/SignsOfAI.Calibration -- paraphrase \\");
        sb.AppendLine("    --paraphrased-by \"<model>\" --instruction Docs/Paraphrase/instruction.md");
        sb.AppendLine("```");

        return sb.ToString();
    }

    private static void AppendLength(
        StringBuilder sb,
        IReadOnlyList<PairMeasurement> pairs,
        IReadOnlyList<PairMeasurement> withFull,
        IReadOnlyList<WindowMeasurement> windows,
        PairManifest manifest,
        double threshold)
    {
        var fullScores = withFull.Select(x => x.FullScore!.Value).OrderBy(s => s).ToList();
        var proseOnly = withFull.Where(x => x.ProseOnlyScore is not null)
            .Select(x => x.ProseOnlyScore!.Value).OrderBy(s => s).ToList();
        int medianWords = (int)Quantile([.. withFull.Select(x => (double)x.FullWords).OrderBy(w => w)], 0.5);

        sb.AppendLine("## Length, which turned out to matter more than rewriting");
        sb.AppendLine();
        sb.AppendLine(
            $"The verdict boundary this build ships was measured on whole documents — a median of " +
            $"{medianWords:N0} words here — and none of them reaches it. Cut {manifest.TargetWords}-word " +
            "windows out of that same writing and some of them do, with no author, subject or sentence " +
            "altered.");
        sb.AppendLine();
        sb.AppendLine("| Window position | Windows | Flagged | Rate | 95% interval | Median score |");
        sb.AppendLine("|---|---|---|---|---|---|");
        // Ordered by where the window sits in the document, not by the spelling of its label — a
        // table that runs late, middle, opening reads as though the trend went the other way.
        foreach (var group in windows.GroupBy(w => w.Position).OrderBy(g => PositionRank(g.Key)))
        {
            var scores = group.Select(w => w.Score).OrderBy(s => s).ToList();
            int flagged = group.Count(w => w.Score >= threshold);
            var (low, high) = Calibrator.WilsonInterval(flagged, group.Count());
            sb.AppendLine($"| {group.Key} | {group.Count()} | {flagged} | {Pct(Rate(flagged, group.Count()))} | " +
                          $"{Pct(low)} – {Pct(high)} | {Quantile(scores, 0.5).ToString("0.0", Inv)} |");
        }
        sb.AppendLine();
        sb.AppendLine(
            "**Where the window falls changes the answer.** The opening of a document scores highest, " +
            "which is not surprising once stated — for a research article that is the abstract and " +
            "introduction, for an encyclopedia entry the lead, and both are the most summary-shaped " +
            "prose their genre contains. The first version of this study cut only from the opening and " +
            "reported the resulting rate as a length effect; it was a length effect with a genre " +
            "effect inside it.");
        sb.AppendLine();

        // The document-level view, which is what a teacher's situation actually looks like: one
        // passage, one verdict, and no way to know which window they happened to be handed.
        var byDoc = pairs.Where(p => p.Windows.Count > 1).ToList();
        int anyFlagged = byDoc.Count(p => p.Windows.Any(w => w.Score >= threshold));
        int allFlagged = byDoc.Count(p => p.Windows.All(w => w.Score >= threshold));

        sb.AppendLine(
            $"Counted by document rather than by window, of the {byDoc.Count} documents that yielded " +
            $"more than one window: **{anyFlagged} are flagged at one position but not another**, and " +
            $"{allFlagged} are flagged wherever the window falls. Whether one of these authors would " +
            "be accused depends on which four hundred words somebody happened to paste.");
        sb.AppendLine();
        sb.AppendLine("| | Median score | 90th percentile | Highest |");
        sb.AppendLine("|---|---|---|---|");
        sb.AppendLine($"| Whole document | {Quantile(fullScores, 0.5).ToString("0.0", Inv)} | " +
                      $"{Quantile(fullScores, 0.9).ToString("0.0", Inv)} | {fullScores[^1].ToString("0.0", Inv)} |");
        if (proseOnly.Count > 0)
        {
            sb.AppendLine($"| Whole document, apparatus stripped | {Quantile(proseOnly, 0.5).ToString("0.0", Inv)} | " +
                          $"{Quantile(proseOnly, 0.9).ToString("0.0", Inv)} | {proseOnly[^1].ToString("0.0", Inv)} |");
        }
        var allWindowScores = windows.Select(w => w.Score).OrderBy(s => s).ToList();
        sb.AppendLine($"| {manifest.TargetWords}-word windows, all positions | {Quantile(allWindowScores, 0.5).ToString("0.0", Inv)} | " +
                      $"{Quantile(allWindowScores, 0.9).ToString("0.0", Inv)} | {allWindowScores[^1].ToString("0.0", Inv)} |");
        sb.AppendLine();
        if (proseOnly.Count > 0)
        {
            int proseFlagged = proseOnly.Count(s => s >= threshold);
            sb.AppendLine(
                $"The second row is a control, and it matters: the whole documents carry figure " +
                "captions and boilerplate that the windows have stripped, so the gap could have been " +
                $"composition rather than length. With the same filter applied and no length cut, " +
                $"{proseFlagged} of {proseOnly.Count} are flagged. It is length.");
            sb.AppendLine();
        }
        sb.AppendLine(
            "The mechanism is not mysterious. Burstiness is the spread of sentence lengths, and a " +
            "short window holds few sentences: the long one with three clauses and the two-word " +
            "fragment that together make a paragraph look human may simply not both be inside it. The " +
            "measurement does not become uncertain, which a reader could allow for. It moves, in one " +
            "direction, toward the machine.");
        sb.AppendLine();
        sb.AppendLine(
            "**This is a defect in this tool, published here because that is what this page is for**, " +
            "and tracked as issue #59. The boundary carries a language condition already — a text in a " +
            "language the corpus never measured gets no verdict — and the reason is exactly the reason " +
            "that applies here: a bound measured on one population must not be spent on another. " +
            "Length is such a population and the code does not yet know it. Until it does, treat a " +
            "verdict on anything short as unmeasured, whatever the interface says.");
        sb.AppendLine();
        sb.AppendLine(
            "One caution about fixing it, which is why #59 is not a one-line change: these windows are " +
            "**cut** from long formal documents, and a student's four-hundred-word answer was " +
            "**composed** at that length. Its sentence lengths are a whole distribution, not a " +
            "truncated one. A floor measured on truncations and enforced against compositions would " +
            "repeat, in a new dimension, the mistake it exists to prevent.");
        sb.AppendLine();
        sb.AppendLine(
            "It also lands on the same ground as the watermark it was written about. Anthropic says " +
            "its mark is unreliable on short samples because few word choices carry little " +
            "information. This tool is unreliable on short samples because few sentences carry little " +
            "rhythm. Two unrelated methods, the same floor, and a teacher holding one paragraph of a " +
            "student's work is below it either way.");
        sb.AppendLine();
    }

    private static void AppendRuleTables(StringBuilder sb, IReadOnlyList<PairMeasurement> pairs)
    {
        var introduced = Movement(pairs, p => p.RewrittenRuleIds, p => p.HumanRuleIds);
        var removed = Movement(pairs, p => p.HumanRuleIds, p => p.RewrittenRuleIds);

        sb.AppendLine("## Which signals the rewrite moved");
        sb.AppendLine();
        AppendMovementTable(sb, "Passages where it appeared only after the rewrite", introduced,
            "Nothing fired after the rewrite that had not fired before it.");
        sb.AppendLine("Signals the rewrite *removed* are worth as much, since a rewrite is not obliged " +
                      "to move in one direction:");
        sb.AppendLine();
        AppendMovementTable(sb, "Passages where it disappeared", removed,
            "Nothing that fired before the rewrite stopped firing after it.");
    }

    private static List<(string RuleId, int Texts)> Movement(
        IReadOnlyList<PairMeasurement> pairs,
        Func<PairMeasurement, IReadOnlyList<string>> after,
        Func<PairMeasurement, IReadOnlyList<string>> before) =>
        [.. pairs
            .SelectMany(p => after(p).Distinct().Except(before(p).Distinct(), StringComparer.Ordinal))
            .GroupBy(id => id, StringComparer.Ordinal)
            .Select(g => (RuleId: g.Key, Texts: g.Count()))
            .OrderByDescending(x => x.Texts)
            .ThenBy(x => x.RuleId, StringComparer.Ordinal)];

    /// <summary>
    /// Prints a movement table, and says how many rows it is not printing.
    ///
    /// The first version capped both tables at twenty silently, and the row it dropped from the
    /// removed table was <c>stat.burstiness</c> — the exact counterweight to the introduced count on
    /// a page arguing that removals matter as much as additions. A cap that hides the row which
    /// undercuts the argument is not a formatting choice.
    /// </summary>
    private static void AppendMovementTable(
        StringBuilder sb, string header, List<(string RuleId, int Texts)> rows, string empty)
    {
        if (rows.Count == 0)
        {
            sb.AppendLine(empty);
            sb.AppendLine();
            return;
        }

        const int cap = 20;
        sb.AppendLine($"| Rule | {header} |");
        sb.AppendLine("|---|---|");
        foreach (var row in rows.Take(cap))
            sb.AppendLine($"| `{row.RuleId}` | {row.Texts} |");
        sb.AppendLine();
        if (rows.Count > cap)
        {
            sb.AppendLine($"*{rows.Count - cap} further rule(s) moved in one passage each and are not " +
                          $"listed: {string.Join(", ", rows.Skip(cap).Select(r => $"`{r.RuleId}`"))}.*");
            sb.AppendLine();
        }
    }

    private static void AppendCharacters(StringBuilder sb, IReadOnlyList<PairMeasurement> pairs)
    {
        int before = pairs.Sum(x => x.HumanArtifacts);
        int after = pairs.Sum(x => x.RewrittenArtifacts);
        var affected = pairs.Where(x => x.HumanArtifacts > 0 || x.RewrittenArtifacts > 0).ToList();
        var codepoints = pairs.SelectMany(x => x.ArtifactCodePoints).Distinct()
            .OrderBy(c => c, StringComparer.Ordinal).ToList();

        sb.AppendLine("## The character layer, which is a different thing");
        sb.AppendLine();
        sb.AppendLine(
            $"The character scanner found {before} suspicious codepoints before the rewrite and " +
            $"{after} after it.");
        sb.AppendLine();
        if (affected.Count > 0)
        {
            sb.AppendLine(
                $"Those totals are not spread across the corpus: they are " +
                $"{(affected.Count == 1 ? "one passage" : $"{affected.Count} passages")} — " +
                $"{string.Join(", ", affected.Select(a => $"`{a.Id}`"))} — and the codepoints are " +
                $"{string.Join(", ", codepoints.Select(c => $"`{c}`"))}. In " +
                $"`{affected[0].Id}` they are Turkish dotless ı inside Turkish proper names, in a " +
                "Spanish article about a Turkish organisation. **That is a false positive of the " +
                "character scanner**, and worth stating on a page that criticises other people's.");
            sb.AppendLine();
        }
        sb.AppendLine(
            "The count not moving is the expected result and worth stating plainly: homoglyphs and " +
            "zero-width characters are a *fingerprint of a tool that touched the file*, not of a model " +
            "that wrote it. Rewriting prose does not produce them, and the free half of every " +
            "watermark-removal service — the half that strips invisible characters — is aimed at a " +
            "layer that has nothing to do with the statistical watermark it advertises removing.");
        sb.AppendLine();
    }

    private static void AppendScoreRow(StringBuilder sb, string label, IReadOnlyList<double> scores)
    {
        var sorted = scores.OrderBy(s => s).ToList();
        sb.AppendLine($"| {label} | {Quantile(sorted, 0.50).ToString("0.0", Inv)} | " +
                      $"{Quantile(sorted, 0.90).ToString("0.0", Inv)} | {sorted[^1].ToString("0.0", Inv)} |");
    }

    private static void AppendGroupTable(
        StringBuilder sb, IEnumerable<IGrouping<string, PairMeasurement>> groups, double threshold)
    {
        sb.AppendLine("| Group | Pairs | Flagged before | Flagged after | Median score change | Median burstiness change |");
        sb.AppendLine("|---|---|---|---|---|---|");
        foreach (var group in groups.OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var members = group.ToList();
            int before = members.Count(x => x.HumanScore >= threshold);
            int after = members.Count(x => x.RewrittenScore >= threshold);
            var scoreDeltas = members.Select(x => x.Delta).OrderBy(d => d).ToList();
            var burstDeltas = members.Select(x => x.RewrittenBurstiness - x.HumanBurstiness).OrderBy(d => d).ToList();

            sb.AppendLine($"| **{group.Key}** | {members.Count} | {before} | {after} | " +
                          $"{Signed(Quantile(scoreDeltas, 0.5))} | {Signed(Quantile(burstDeltas, 0.5), "0.00")} |");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// McNemar's test in its exact form: given the pairs that changed, how surprising is it that this
    /// many of them changed in one direction? The chi-square approximation is not usable at these
    /// counts, and reporting a p-value that the sample cannot support is the failure this project
    /// objects to in other people's numbers. Also serves as the exact sign test, which is the same
    /// computation on a different pair of counts.
    /// </summary>
    private static double ExactBinomialTwoSided(int successes, int trials)
    {
        if (trials == 0) return 1.0;

        double Pmf(int k)
        {
            double logC = 0;
            for (int i = 1; i <= k; i++) logC += Math.Log(trials - k + i) - Math.Log(i);
            return Math.Exp(logC - trials * Math.Log(2));
        }

        double observed = Pmf(successes);
        double total = 0;

        // Sum every outcome no more likely than the one observed, which is the two-sided p-value for a
        // discrete distribution — halving a one-sided value would be wrong for an asymmetric tail.
        for (int k = 0; k <= trials; k++)
        {
            var pk = Pmf(k);
            if (pk <= observed * (1 + 1e-9)) total += pk;
        }

        return Math.Min(1.0, total);
    }

    /// <summary>
    /// Wilcoxon signed-rank, normal approximation with a tie correction.
    ///
    /// Reported *beside* the sign test rather than instead of it. The sign test counts directions and
    /// the signed-rank test also weighs magnitudes, so on a sample where most changes are tiny they
    /// disagree — and neither was chosen before the data were seen. Printing both, and saying so, is
    /// the only honest way to present a result whose significance depends on that choice.
    /// </summary>
    private static double WilcoxonSignedRank(IReadOnlyList<double> differences)
    {
        var nonZero = differences.Where(d => Math.Abs(d) > 1e-9).ToList();
        int n = nonZero.Count;
        if (n < 6) return 1.0;

        var ordered = nonZero
            .Select((d, i) => (Value: d, Abs: Math.Abs(d), Index: i))
            .OrderBy(x => x.Abs)
            .ToList();

        var ranks = new double[n];
        int position = 0;
        double tieCorrection = 0;

        while (position < n)
        {
            int end = position;
            while (end + 1 < n && Math.Abs(ordered[end + 1].Abs - ordered[position].Abs) < 1e-9) end++;

            double averageRank = (position + end + 2) / 2.0;
            int size = end - position + 1;
            for (int i = position; i <= end; i++) ranks[i] = averageRank;
            if (size > 1) tieCorrection += size * (double)size * size - size;

            position = end + 1;
        }

        double positive = 0;
        for (int i = 0; i < n; i++) if (ordered[i].Value > 0) positive += ranks[i];

        double mean = n * (n + 1) / 4.0;
        double variance = (n * (n + 1) * (2.0 * n + 1) - tieCorrection / 2.0) / 24.0;
        if (variance <= 0) return 1.0;

        // Continuity correction, because a discrete statistic is being read off a continuous curve.
        double z = (Math.Abs(positive - mean) - 0.5) / Math.Sqrt(variance);
        return Math.Min(1.0, 2 * (1 - NormalCdf(z)));
    }

    private static double NormalCdf(double z)
    {
        // Abramowitz and Stegun 7.1.26 on the error function; ample for a p-value printed to three
        // decimal places.
        double t = 1 / (1 + 0.2316419 * Math.Abs(z));
        double d = 0.3989422804014327 * Math.Exp(-z * z / 2);
        double p = d * t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 +
                   t * (-1.821255978 + t * 1.330274429))));
        return z >= 0 ? 1 - p : p;
    }

    /// <summary>
    /// A distribution-free interval for the median, from the binomial order statistics.
    ///
    /// No bootstrap, so no random number generator and no seed to remember: the same data give the
    /// same interval on any machine, which is what a page regenerated from a manifest requires.
    /// </summary>
    private static (double Low, double High) MedianInterval(IReadOnlyList<double> sorted)
    {
        int n = sorted.Count;
        if (n < 6) return (sorted.Count > 0 ? sorted[0] : 0, sorted.Count > 0 ? sorted[^1] : 0);

        // Largest k with P(X < k) <= 0.025 under Binomial(n, 0.5): the conventional exact interval.
        int k = 0;
        double cumulative = 0;
        for (int i = 0; i <= n; i++)
        {
            double logC = 0;
            for (int j = 1; j <= i; j++) logC += Math.Log(n - i + j) - Math.Log(j);
            cumulative += Math.Exp(logC - n * Math.Log(2));
            if (cumulative > 0.025) { k = i; break; }
        }

        int low = Math.Max(0, k - 1);
        int high = Math.Min(n - 1, n - k);
        return (sorted[low], sorted[high]);
    }

    private static double Quantile(IReadOnlyList<double> sorted, double q)
    {
        if (sorted.Count == 0) return 0;
        var index = (sorted.Count - 1) * q;
        int lower = (int)Math.Floor(index), upper = (int)Math.Ceiling(index);
        return lower == upper ? sorted[lower] : sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower);
    }

    /// <summary>Reading order for the window labels, so the table runs front to back.</summary>
    private static int PositionRank(string label) => label switch
    {
        "opening" => 0,
        "middle" => 1,
        "late" => 2,
        _ => 3,
    };

    private static double Rate(int flagged, int total) => total == 0 ? 0 : (double)flagged / total;

    private static string Wilson(int flagged, int total)
    {
        var (low, high) = Calibrator.WilsonInterval(flagged, total);
        return $"{Pct(low)} – {Pct(high)}";
    }

    private static string Pct(double value) => (value * 100).ToString("0.#", Inv) + "%";

    private static string Signed(double value, string format = "0.0") =>
        (value > 0 ? "+" : "") + value.ToString(format, Inv);

    private static string FormatP(double p) =>
        p < 0.001 ? "p < 0.001" : "p = " + p.ToString("0.###", Inv);
}
