using System.Globalization;
using System.Text;
using SignsOfAI.Core.Calibration;

namespace SignsOfAI.Calibration;

/// <summary>
/// Renders the measurement as a page a stranger can argue with.
///
/// The output is committed to the repository on purpose. A false-positive rate that lives on
/// somebody's laptop is a marketing claim; one that sits next to the corpus manifest and the code
/// that produced it is a result. Every number here carries its interval, and the page says what the
/// numbers cannot support as clearly as what they can.
/// </summary>
public static class Report
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Render(CalibrationResult r, CorpusManifest manifest, string version, string generatedOn)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# How often this tool is wrong about a human");
        sb.AppendLine();
        sb.AppendLine("<!-- Generated by tools/SignsOfAI.Calibration. Do not edit by hand: re-run it. -->");
        sb.AppendLine();
        sb.AppendLine(
            "Every AI detector is asked the same question by every teacher who picks one up: *how often " +
            "are you wrong?* None of them answer it. This is our answer, and the method is in the " +
            "repository next to it.");
        sb.AppendLine();
        sb.AppendLine(
            "It is **not an accuracy figure**. Accuracy needs machine-written text to measure against, " +
            "and any collection of that is a sample of whichever models were convenient in whichever " +
            "month — a number that ages badly and flatters whoever assembled it. What follows needs only " +
            "writing known to be human, which does not go stale, and it measures the harm this category " +
            "actually causes: detectors flag 61% of essays by non-native English speakers, and not one of " +
            "them publishes that figure about itself.");
        sb.AppendLine();

        // ---- what was measured -------------------------------------------------------------------
        sb.AppendLine("## What was measured");
        sb.AppendLine();
        sb.AppendLine($"- **Corpus** `{manifest.Id}`, fingerprint `{r.CorpusHash}`");
        sb.AppendLine($"- **Texts** {r.Overall.Count:N0} ({r.Overall.TotalWords:N0} words)");
        sb.AppendLine($"- **Engine** {version}");
        sb.AppendLine($"- **Run** {generatedOn}");
        sb.AppendLine($"- **Target false-positive rate** {Pct(r.TargetFalsePositiveRate)}");
        sb.AppendLine();
        sb.AppendLine(
            "Every text here was published before generative models could have written it. That is the " +
            "whole basis for calling it human, and it is a stronger guarantee than any classifier offers " +
            "about anything. The manifest names each source, its licence and its year, so the claim can " +
            "be traced rather than trusted.");
        sb.AppendLine();

        if (r.Overall.Count == 0)
        {
            sb.AppendLine("**The corpus is empty, so there is nothing to report yet.** " +
                          "See `Docs/Calibration/README.md` for how to assemble one.");
            return sb.ToString();
        }

        // ---- the headline ------------------------------------------------------------------------
        sb.AppendLine("## The headline");
        sb.AppendLine();
        sb.AppendLine(Headline(r.Overall, r.TargetFalsePositiveRate));
        sb.AppendLine();
        sb.AppendLine(
            "Read the interval, not the percentage. On a small corpus an observed rate is compatible " +
            "with a much wider range, and the recommendation below is made from the **upper** end of " +
            "that range rather than the flattering one — so it stays cautious while the corpus is thin " +
            "and tightens on its own as it grows.");
        sb.AppendLine();

        // ---- per group ---------------------------------------------------------------------------
        sb.AppendLine("## By language");
        sb.AppendLine();
        sb.AppendLine("A rate that holds in English and fails in Spanish is not one number, and reporting " +
                      "it as one would hide exactly the failure that matters here.");
        sb.AppendLine();
        AppendGroups(sb, r.ByLanguage, r.TargetFalsePositiveRate);

        sb.AppendLine("## By writer");
        sb.AppendLine();
        sb.AppendLine("The reason the whole exercise exists. If this project cannot show a rate for " +
                      "second-language writers that is comparable to the rate for everyone else, it has " +
                      "the same defect as every tool it criticises, and should say so.");
        sb.AppendLine();
        AppendGroups(sb, r.ByStratum, r.TargetFalsePositiveRate);
        sb.AppendLine(Spread(r.ByStratum));
        sb.AppendLine();

        // ---- the curve ---------------------------------------------------------------------------
        sb.AppendLine("## Every threshold");
        sb.AppendLine();
        sb.AppendLine("| Score at or above | Human texts flagged | Rate | 95% interval |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var row in r.Overall.Thresholds)
        {
            sb.AppendLine($"| {row.Threshold.ToString("0", Inv)} | {row.Flagged} / {row.Total} | " +
                          $"{Pct(row.Rate)} | {Pct(row.RateLow)} – {Pct(row.RateHigh)} |");
        }
        sb.AppendLine();

        // ---- rules -------------------------------------------------------------------------------
        if (r.RuleFalsePositives.Count > 0)
        {
            sb.AppendLine("## Which rules misfire");
            sb.AppendLine();
            sb.AppendLine("Every rule below fired on text no machine wrote, so each hit is a false positive " +
                          "by construction — there is no judgement call to make. This is the most " +
                          "immediately useful thing the exercise produces: it turns \"our rules probably " +
                          "have false positives somewhere\" into a ranked list.");
            sb.AppendLine();
            sb.AppendLine("| Rule | Texts it fired on | Share | Total hits |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var rule in r.RuleFalsePositives.Take(25))
            {
                sb.AppendLine($"| `{rule.RuleId}` | {rule.Texts} | {Pct(rule.TextShare)} | {rule.Occurrences} |");
            }
            sb.AppendLine();
            sb.AppendLine("A rule near the top is not automatically wrong. Some tells genuinely appear in " +
                          "human academic prose and the catalog says so. But a rule firing on most human " +
                          "texts is measuring the genre rather than the machine, and should be reweighted " +
                          "or retired.");
            sb.AppendLine();
        }

        // ---- limits ------------------------------------------------------------------------------
        sb.AppendLine("## What this does not tell you");
        sb.AppendLine();
        sb.AppendLine("- **Nothing about how much AI writing it catches.** That is the other half of the " +
                      "picture and it is not measured here, deliberately. A tool that flags nothing has a " +
                      "perfect false-positive rate.");
        sb.AppendLine("- **Nothing about text unlike this corpus.** These are published articles. A " +
                      "first-year essay is shorter, looser and differently edited, and the rate on one " +
                      "does not transfer to the other. Calibrating on your own students' pre-2022 work is " +
                      "the fix, and the same tool does it.");
        sb.AppendLine("- **The grouping of writers is a proxy, not a fact.** Nobody's first language is " +
                      "recorded in a DOI. The manifest states the reasoning per text so it can be " +
                      "argued with; where it is wrong, the number moves.");
        sb.AppendLine("- **Hashes prove what *this* run measured**, not that another person extracting the " +
                      "same articles would get identical text. They would not: PDF and HTML extraction " +
                      "differ. Reproducing this needs the extracted texts, not just the manifest.");
        sb.AppendLine();
        sb.AppendLine("Re-run it yourself:");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("dotnet run --project tools/SignsOfAI.Calibration -- run \\");
        sb.AppendLine("    --manifest Docs/Calibration/corpus.json --texts <your texts dir>");
        sb.AppendLine("```");

        return sb.ToString();
    }

    private static void AppendGroups(StringBuilder sb, IReadOnlyList<StratumCalibration> groups, double target)
    {
        sb.AppendLine("| Group | Texts | Median | 90th pct | Highest | Threshold for " + Pct(target) +
                      " | Best bound it can support |");
        sb.AppendLine("|---|---|---|---|---|---|---|");
        foreach (var g in groups)
        {
            var threshold = g.ThresholdForTarget is { } t
                ? t.ToString("0", Inv)
                : "—";
            // A group too small for the promise is not a group with nothing to say: the tightest
            // bound it does reach is the honest version of "how far this many texts gets you".
            var best = g.Thresholds.Count == 0 ? "—" : Pct(g.Thresholds.Min(x => x.RateHigh));
            sb.AppendLine($"| **{g.Name}** | {g.Count} | {g.MedianScore.ToString("0.0", Inv)} | " +
                          $"{g.NinetiethScore.ToString("0.0", Inv)} | {g.HighestScore.ToString("0.0", Inv)} | " +
                          $"{threshold} | {best} |");
        }
        sb.AppendLine();
        sb.AppendLine("A dash means this group has too few texts to bound that rate at all — with nothing " +
                      "flagged it still takes roughly seventy-five before the interval alone gets under 5%. " +
                      "That is a statement about the corpus, not the tool.");
        sb.AppendLine();
    }

    /// <summary>
    /// States, from the numbers rather than from hope, whether any group is being treated worse. A
    /// systematic penalty against second-language writers would show as one group sitting clearly
    /// above the others — that is what this sentence is for, and it will say so if it ever happens.
    /// </summary>
    private static string Spread(IReadOnlyList<StratumCalibration> groups)
    {
        var usable = groups.Where(g => g.Count > 0).ToList();
        if (usable.Count < 2) return "";

        var lowMedian = usable.MinBy(g => g.MedianScore)!;
        var highMedian = usable.MaxBy(g => g.MedianScore)!;
        var highTail = usable.MaxBy(g => g.NinetiethScore)!;

        return
            $"Across these groups the median score runs from {highMedian.MedianScore.ToString("0.0", Inv)} " +
            $"(**{highMedian.Name}**) down to {lowMedian.MedianScore.ToString("0.0", Inv)} " +
            $"(**{lowMedian.Name}**), a spread of " +
            $"{(highMedian.MedianScore - lowMedian.MedianScore).ToString("0.0", Inv)} points on a scale " +
            "of a hundred. The longest tail belongs to **" + highTail.Name + "** at " +
            $"{highTail.NinetiethScore.ToString("0.0", Inv)} for the ninetieth percentile. " +
            "A tool with the defect this project criticises would show one group sitting well above the " +
            "rest; on this corpus none does. It is a first indication rather than a finding — these are " +
            "tens of texts, not hundreds — and the numbers move as the corpus grows, in whichever " +
            "direction they move.";
    }

    private static string Headline(StratumCalibration overall, double target)
    {
        if (overall.ThresholdForTarget is { } t)
        {
            var row = overall.Thresholds.First(x => Math.Abs(x.Threshold - t) < 1e-9);
            return $"**At a threshold of {t.ToString("0", Inv)}/100, this tool flags at most " +
                   $"{Pct(target)} of writing known to be human** — {row.Flagged} of {row.Total} texts " +
                   $"in this corpus, an observed {Pct(row.Rate)} with a 95% interval of " +
                   $"{Pct(row.RateLow)} – {Pct(row.RateHigh)}.";
        }

        var best = overall.Thresholds.OrderBy(x => x.RateHigh).FirstOrDefault();
        return best is null
            ? "**This corpus is too small to support any promise.**"
            : $"**This corpus cannot yet support a {Pct(target)} promise at any threshold.** The best it " +
              $"reaches is {Pct(best.RateHigh)} at the upper bound, at a threshold of " +
              $"{best.Threshold.ToString("0", Inv)}/100 ({best.Flagged} of {best.Total} texts flagged). " +
              "That is a statement about the size of the corpus, not about the tool — a clean run needs " +
              "roughly seventy-five texts before the interval alone can bound a 5% rate. More texts is " +
              "the entire fix, and the manifest takes pull requests.";
    }

    private static string Pct(double value) => (value * 100).ToString("0.#", Inv) + "%";
}
