using System.Globalization;
using System.Text;
using SignsOfAI.Core.Calibration;

namespace SignsOfAI.Calibration;

/// <summary>
/// Renders the measurement as a page a stranger can argue with.
///
/// The output is committed to the repository on purpose. A false-positive rate that lives on
/// somebody's laptop is a marketing claim; one that sits next to the corpus manifest and the code
/// that produced it is a result. Every number here carries its interval, and the page says what the
/// numbers cannot support as clearly as what they can.
/// </summary>
public static class Report
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Render(CalibrationResult r, CorpusManifest manifest, string version, string generatedOn)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# How often this tool is wrong about a human");
        sb.AppendLine();
        sb.AppendLine("<!-- Generated by tools/SignsOfAI.Calibration. Do not edit by hand: re-run it. -->");
        sb.AppendLine();
        sb.AppendLine(
            "Every AI detector is asked the same question by every teacher who picks one up: *how often " +
            "are you wrong?* None of them answer it. This is our answer, and the method is in the " +
            "repository next to it.");
        sb.AppendLine();
        sb.AppendLine(
            "It is **not an accuracy figure**. Accuracy needs machine-written text to measure against, " +
            "and any collection of that is a sample of whichever models were convenient in whichever " +
            "month — a number that ages badly and flatters whoever assembled it. What follows needs only " +
            "writing known to be human, which does not go stale, and it measures the harm this category " +
            "actually causes: detectors flag 61% of essays by non-native English speakers, and not one of " +
            "them publishes that figure about itself.");
        sb.AppendLine();

        // ---- what was measured -------------------------------------------------------------------
        sb.AppendLine("## What was measured");
        sb.AppendLine();
        sb.AppendLine($"- **Corpus** `{manifest.Id}`, fingerprint `{r.CorpusHash}`");
        sb.AppendLine($"- **Texts** {r.Overall.Count:N0} ({r.Overall.TotalWords:N0} words)");
        sb.AppendLine($"- **Lengths measured** {r.Overall.ShortestWords:N0} – {r.Overall.LongestWords:N0} words " +
                      $"(median {r.Overall.MedianWords:N0})");
        sb.AppendLine($"- **Engine** {version}");
        sb.AppendLine($"- **Run** {generatedOn}");
        sb.AppendLine($"- **Target false-positive rate** {Pct(r.TargetFalsePositiveRate)}");
        sb.AppendLine();
        sb.AppendLine(
            "Every text here was written before generative models could have written it — articles and " +
            "encyclopedia revisions with a date, and classroom essays from a learner corpus collected " +
            "years earlier. That is the whole basis for calling it human, and it is a stronger guarantee " +
            "than any classifier offers about anything. The manifest names each source, its licence and " +
            "its year, so the claim can be traced rather than trusted.");
        sb.AppendLine();
        AppendSources(sb, manifest);

        if (r.Overall.Count == 0)
        {
            sb.AppendLine("**The corpus is empty, so there is nothing to report yet.** " +
                          "See `Docs/Calibration/README.md` for how to assemble one.");
            return sb.ToString();
        }

        // ---- the headline ------------------------------------------------------------------------
        sb.AppendLine("## The headline");
        sb.AppendLine();
        sb.AppendLine(Headline(r.Overall, r.TargetFalsePositiveRate));
        sb.AppendLine();
        sb.AppendLine(
            $"**It covers documents of {r.Overall.ShortestWords:N0} words and up, because that is what was " +
            "measured.** Nothing shorter was: the corpus has no text below that length, so the boundary " +
            "below is not supported there and the tool withholds its verdict rather than extrapolating. " +
            "That is a statement about coverage, not about where the tool breaks — though the direction " +
            "of the length effect *has* been measured, and it goes the wrong way: the same documents " +
            "flagged 0 of 32 whole and 6 of 32 as 400-word excerpts of themselves " +
            "(`Docs/PARAPHRASE.md`, section *Length*). Lowering this floor means measuring short writing " +
            "people actually composed at that length, not slicing long documents into pieces.");
        sb.AppendLine();
        sb.AppendLine(
            "Read the interval, not the percentage. On a small corpus an observed rate is compatible " +
            "with a much wider range, and the recommendation below is made from the **upper** end of " +
            "that range rather than the flattering one — so it stays cautious while the corpus is thin " +
            "and tightens on its own as it grows.");
        sb.AppendLine();

        // ---- per group ---------------------------------------------------------------------------
        sb.AppendLine("## By language");
        sb.AppendLine();
        sb.AppendLine("A rate that holds in English and fails in Spanish is not one number, and reporting " +
                      "it as one would hide exactly the failure that matters here.");
        sb.AppendLine();
        AppendGroups(sb, r.ByLanguage, r.TargetFalsePositiveRate);

        sb.AppendLine("## By writer");
        sb.AppendLine();
        sb.AppendLine("The reason the whole exercise exists. If this project cannot show a rate for " +
                      "second-language writers that is comparable to the rate for everyone else, it has " +
                      "the same defect as every tool it criticises, and should say so.");
        sb.AppendLine();
        AppendGroups(sb, r.ByStratum, r.TargetFalsePositiveRate);
        sb.AppendLine(Spread(r.ByStratum, r.Overall.ThresholdForTarget));
        sb.AppendLine();

        // ---- the curve ---------------------------------------------------------------------------
        sb.AppendLine("## Every threshold");
        sb.AppendLine();
        sb.AppendLine("| Score at or above | Human texts flagged | Rate | 95% interval |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var row in r.Overall.Thresholds)
        {
            sb.AppendLine($"| {row.Threshold.ToString("0", Inv)} | {row.Flagged} / {row.Total} | " +
                          $"{Pct(row.Rate)} | {Pct(row.RateLow)} – {Pct(row.RateHigh)} |");
        }
        sb.AppendLine();

        // ---- what the product does with the number ------------------------------------------------
        // Written here rather than left to the reader, because the gap between the measured figure and
        // the shipped wording is precisely what this project criticises in other tools, and a page that
        // publishes the figure without saying what the product does with it invites the same charge.
        sb.AppendLine("## What the product does with this number");
        sb.AppendLine();
        if (r.Overall.ThresholdForTarget is { } recommended)
        {
            sb.AppendLine(
                $"The tool speaks at **{recommended.ToString("0.#", Inv)}/100** and nowhere else, taking the " +
                "boundary from the table above rather than from anybody's judgement. Below it a document " +
                "gets its score and the reason it gets nothing more: a low score is not evidence that a " +
                "person wrote something, since a detector that detects nothing also returns a low score, " +
                "and this project has deliberately never measured how much machine writing it catches. " +
                "The boundary moves when this page moves — including upward if a larger corpus turns out " +
                "to be less flattering.");
            sb.AppendLine();
            sb.AppendLine(
                "Above it there is **one** verdict, not a scale of them. This corpus can place a boundary " +
                "and can say nothing whatever about how much further past it a score has travelled: no " +
                "text known to be human came close to the upper reaches, and grading \"moderate\" against " +
                "\"strong\" would need machine-written text, which the opening of this page argues against " +
                "collecting. Interfaces do shade a high score more urgently than a low one, and those " +
                "shades are a display convention — they are not on this page because nothing measured " +
                "them.");
            sb.AppendLine();
            sb.AppendLine(
                "A language absent from the corpus entirely gets no verdict at all, whatever it scores. " +
                "A language present but too thin to bound its own rate borrows this boundary and carries " +
                "its own figure beside it, so the reader weighs the rate that was measured for the " +
                "writing in front of them rather than the pooled one.");
        }
        else
        {
            sb.AppendLine(
                "This corpus supports no threshold, so the tool renders no verdict at any score. It " +
                "reports what it found and says the boundary is unmeasured, which is the honest output " +
                "of an unmeasured build and the reason this section is not silently omitted.");
        }
        sb.AppendLine();

        // ---- rules -------------------------------------------------------------------------------
        if (r.RuleFalsePositives.Count > 0)
        {
            sb.AppendLine("## Which rules misfire");
            sb.AppendLine();
            sb.AppendLine("Every rule below fired on text no machine wrote, so each hit is a false positive " +
                          "by construction — there is no judgement call to make. This is the most " +
                          "immediately useful thing the exercise produces: it turns \"our rules probably " +
                          "have false positives somewhere\" into a ranked list.");
            sb.AppendLine();
            sb.AppendLine("| Rule | Texts it fired on | Share | Total hits |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var rule in r.RuleFalsePositives.Take(25))
            {
                sb.AppendLine($"| `{rule.RuleId}` | {rule.Texts} | {Pct(rule.TextShare)} | {rule.Occurrences} |");
            }
            sb.AppendLine();
            sb.AppendLine("A rule near the top is not automatically wrong. Some tells genuinely appear in " +
                          "human academic prose and the catalog says so. But a rule firing on most human " +
                          "texts is measuring the genre rather than the machine, and should be reweighted " +
                          "or retired.");
            sb.AppendLine();
        }

        // ---- limits ------------------------------------------------------------------------------
        sb.AppendLine("## What this does not tell you");
        sb.AppendLine();
        sb.AppendLine("- **Nothing about how much AI writing it catches.** That is the other half of the " +
                      "picture and it is not measured here, deliberately. A tool that flags nothing has a " +
                      "perfect false-positive rate.");
        sb.AppendLine("- **Nothing about text unlike this corpus.** These are published articles and " +
                      "the essays of adult learners in a university English programme. A first-year " +
                      "essay by a native speaker is a different population again, and the rate on one " +
                      "does not transfer to the other. Calibrating on your own students' pre-2022 work is " +
                      "the fix, and the same tool does it.");
        sb.AppendLine("- **The affiliation groups are a proxy, not a fact.** Nobody's first language is " +
                      "recorded in a DOI. The learner group is the exception — its corpus records each " +
                      "writer's first language — which is why it exists. Elsewhere the manifest states " +
                      "the reasoning per text so it can be argued with; where it is wrong, the number moves.");
        sb.AppendLine("- **Hashes prove what *this* run measured**, not that another person extracting the " +
                      "same articles would get identical text. They would not: PDF and HTML extraction " +
                      "differ. Reproducing this needs the extracted texts, not just the manifest.");
        sb.AppendLine();
        sb.AppendLine("Re-run it yourself:");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("dotnet run --project tools/SignsOfAI.Calibration -- run \\");
        sb.AppendLine("    --manifest Docs/Calibration/corpus.json --texts <your texts dir>");
        sb.AppendLine("```");

        return sb.ToString();
    }

    private static void AppendGroups(StringBuilder sb, IReadOnlyList<StratumCalibration> groups, double target)
    {
        sb.AppendLine("| Group | Texts | Median | 90th pct | Highest | Threshold for " + Pct(target) +
                      " | Best bound it can support |");
        sb.AppendLine("|---|---|---|---|---|---|---|");
        foreach (var g in groups)
        {
            var threshold = g.ThresholdForTarget is { } t
                ? t.ToString("0", Inv)
                : "—";
            // A group too small for the promise is not a group with nothing to say: the tightest
            // bound it does reach is the honest version of "how far this many texts gets you".
            var best = g.Thresholds.Count == 0 ? "—" : Pct(g.Thresholds.Min(x => x.RateHigh));
            sb.AppendLine($"| **{g.Name}** | {g.Count} | {g.MedianScore.ToString("0.0", Inv)} | " +
                          $"{g.NinetiethScore.ToString("0.0", Inv)} | {g.HighestScore.ToString("0.0", Inv)} | " +
                          $"{threshold} | {best} |");
        }
        sb.AppendLine();
        sb.AppendLine("A dash means this group has too few texts to bound that rate at all — with nothing " +
                      "flagged it still takes roughly seventy-five before the interval alone gets under 5%. " +
                      "That is a statement about the corpus, not the tool.");
        sb.AppendLine();
    }

    /// <summary>
    /// <summary>
    /// Who wrote the corpus, by group, with the citation each licence asks for. Attribution is not a
    /// courtesy here: three of the four sources are CC BY of some flavour, and a page that quotes
    /// numbers measured on somebody's corpus without naming them is in breach of the one condition
    /// they set.
    /// </summary>
    private static void AppendSources(StringBuilder sb, CorpusManifest manifest)
    {
        sb.AppendLine("### Sources");
        sb.AppendLine();
        sb.AppendLine("| Group | Texts | Licence | Source |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var group in manifest.Texts.GroupBy(t => t.Stratum).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var licences = string.Join(", ", group.Select(t => t.License).Distinct().OrderBy(l => l, StringComparer.Ordinal));
            sb.AppendLine($"| **{group.Key}** | {group.Count()} | {licences} | {Describe(group.ToList())} |");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// The citation for a group, from what the manifest records. Sources that are one work with one
    /// DOI get the work's citation; sources that are many works get the pointer to where each one is.
    /// </summary>
    private static string Describe(IReadOnlyList<CorpusEntry> entries)
    {
        var dois = entries.Select(e => e.Doi).Where(d => !string.IsNullOrEmpty(d)).Distinct().ToList();
        if (dois.Count == 1 && dois[0] == "10.5281/zenodo.3991977")
            return "Juffs, A., Han, N.-R. & Naismith, B. (2020). *The University of Pittsburgh English " +
                   "Language Institute Corpus (PELIC)*, v1.0. doi:10.5281/zenodo.3991977 — classroom " +
                   "essays, first submitted version, one per student";
        if (dois.Count > 1)
            return $"{dois.Count} open-access research articles from PLOS; each DOI is in the manifest";
        var hosts = entries.Select(e => e.Url is null ? null : new Uri(e.Url).Host).Where(h => h is not null).Distinct().ToList();
        return hosts.Count == 1
            ? $"revisions of {hosts[0]}; each revision URL is in the manifest"
            : "see the manifest";
    }

    /// States, from the numbers rather than from hope, whether any group is being treated worse. A
    /// systematic penalty against second-language writers would show as one group sitting clearly
    /// above the others — that is what this paragraph is for, and it says so when it happens.
    /// </summary>
    private static string Spread(IReadOnlyList<StratumCalibration> groups, double? boundary)
    {
        var usable = groups.Where(g => g.Count > 0).ToList();
        if (usable.Count < 2) return "";

        var lowMedian = usable.MinBy(g => g.MedianScore)!;
        var highMedian = usable.MaxBy(g => g.MedianScore)!;
        var highTail = usable.MaxBy(g => g.NinetiethScore)!;

        var sb = new StringBuilder();
        sb.Append($"Across these groups the median score runs from {highMedian.MedianScore.ToString("0.0", Inv)} " +
                  $"(**{highMedian.Name}**) down to {lowMedian.MedianScore.ToString("0.0", Inv)} " +
                  $"(**{lowMedian.Name}**), a spread of " +
                  $"{(highMedian.MedianScore - lowMedian.MedianScore).ToString("0.0", Inv)} points on a scale " +
                  "of a hundred. The longest tail belongs to **" + highTail.Name + "** at " +
                  $"{highTail.NinetiethScore.ToString("0.0", Inv)} for the ninetieth percentile. ");

        // The sentence that matters is decided at the boundary the page recommends, because that is
        // the only place a difference between groups turns into a different verdict for a person.
        // A group with no row at the boundary was not measured there, which is not the same as
        // being flagged nothing — a reviewer produced the wrong sentence with a synthetic group.
        var measured = boundary is { } b
            ? usable.Select(g => (Group: g, Row: g.Thresholds.FirstOrDefault(t => Math.Abs(t.Threshold - b) < 0.001)))
                    .Where(x => x.Row is not null)
                    .Select(x => (x.Group, Row: x.Row!))
                    .ToList()
            : [];
        var unmeasured = usable.Where(g => measured.All(m => m.Group != g)).ToList();
        var flagged = measured.Where(x => x.Row.Flagged > 0).OrderByDescending(x => x.Row.Rate).ToList();

        if (boundary is { } bound && flagged.Count > 0)
        {
            var (top, row) = flagged[0];
            var also = top == highMedian && top == highTail
                ? " It also sits highest in median and ninetieth percentile."
                : "";
            sb.Append($"At the boundary this page recommends, {bound:0}/100, ");
            sb.Append(string.Join(" and ", flagged.Select(f =>
                $"**{f.Group.Name}** is flagged {f.Row.Flagged} of {f.Group.Count} " +
                $"({Pct(f.Row.Rate)}, interval {Pct(f.Row.RateLow)} – {Pct(f.Row.RateHigh)})")));
            var clean = measured.Count - flagged.Count;
            sb.Append(clean == 0
                ? "."
                : clean == 1
                    ? "; the one other group measured there is flagged nothing at all."
                    : $"; the other {clean} groups measured there are flagged nothing at all.");
            if (unmeasured.Count > 0)
                sb.Append(" " + string.Join(", ", unmeasured.Select(g => $"**{g.Name}**")) +
                          (unmeasured.Count == 1 ? " has" : " have") + " no row at that boundary and cannot be compared.");
            sb.Append(also);

            // The boundary is where it is because of what happens one step below it; a page that
            // shows only the recommended step hides the very thing that moved it.
            var below = top.Thresholds.Where(t => t.Threshold < bound).OrderByDescending(t => t.Threshold).FirstOrDefault();
            if (below is not null && below.Flagged > row.Flagged)
                sb.Append($" One step down, at {below.Threshold:0}/100, **{top.Name}** would be flagged " +
                          $"{below.Flagged} of {top.Count} ({Pct(below.Rate)}, interval {Pct(below.RateLow)} – " +
                          $"{Pct(below.RateHigh)}); that step is why the boundary sits where it does.");
            sb.Append(" That is the shape of the defect this project criticises, and it is reported here " +
                      "rather than averaged away — smaller than the figures published for other tools, " +
                      "which is a comparison, not an excuse.");
        }
        else if (boundary is { } noneAt && measured.Count > 0)
        {
            sb.Append($"At the boundary this page recommends, {noneAt:0}/100, no group measured there is " +
                      "flagged at all. A tool with the defect this project criticises would show one group " +
                      "sitting well above the rest; on this corpus none does.");
        }
        else
        {
            sb.Append("No boundary is recommended yet, so the groups cannot be compared where it would " +
                      "matter; the medians above are the only comparison available.");
        }

        sb.Append(" The groups run from tens of texts to a couple of hundred, and the numbers move as " +
                  "the corpus grows, in whichever direction they move.");
        return sb.ToString();
    }

    private static string Headline(StratumCalibration overall, double target)
    {
        if (overall.ThresholdForTarget is { } t)
        {
            var row = overall.Thresholds.First(x => Math.Abs(x.Threshold - t) < 1e-9);
            return $"**At a threshold of {t.ToString("0", Inv)}/100, this tool flags at most " +
                   $"{Pct(target)} of writing known to be human** — {row.Flagged} of {row.Total} texts " +
                   $"in this corpus, an observed {Pct(row.Rate)} with a 95% interval of " +
                   $"{Pct(row.RateLow)} – {Pct(row.RateHigh)}.";
        }

        var best = overall.Thresholds.OrderBy(x => x.RateHigh).FirstOrDefault();
        return best is null
            ? "**This corpus is too small to support any promise.**"
            : $"**This corpus cannot yet support a {Pct(target)} promise at any threshold.** The best it " +
              $"reaches is {Pct(best.RateHigh)} at the upper bound, at a threshold of " +
              $"{best.Threshold.ToString("0", Inv)}/100 ({best.Flagged} of {best.Total} texts flagged). " +
              "That is a statement about the size of the corpus, not about the tool — a clean run needs " +
              "roughly seventy-five texts before the interval alone can bound a 5% rate. More texts is " +
              "the entire fix, and the manifest takes pull requests.";
    }

    private static string Pct(double value) => (value * 100).ToString("0.#", Inv) + "%";
}
